### PR TITLE
Code Overhaul (was "improve commenting #1")

### PR DESCRIPTION
**Pull request by csBlueChip**
Trying to get my head around this code so it can be used in a fairly heavy-duty project.
Thought some code cleanup was a good place to start.
I have a habit of commiting lots of tiny changes because it reduces the risk of mistakes.

Part 1.
"Clearly mark the start of every function to aid is source navigation & code maintainability."
I have also noticed that my editor has removed all the trailing spaces from the code, sorry about that, it wasn't intentional, but it is done now
BC

### CODE REVIEW

**Comment by csBlueChip** [comment]
Second commit standardises the commenting style for a consistent coding style
I have also used "#if 0" instead of "/*...*/" to enable/disable debug code, this way it can be enabled/disabled by changing the 1 for a 0 (and vice versa ) which is easier than changing the comment status at the beginning and end of the block in question

**Comment by csBlueChip** [comment]
A few different styles were being used to declare functions, this just pulls them all in to a single coding style

**Comment by csBlueChip** [comment]
Most (not all) "one line ifs" were constructed as:
if (foo) {
  bar();
}
I have gone through and reduced the ones which were spread over three lines of code
if (foo)  bar() ;

**Comment by csBlueChip** [comment]
Implemented DBG_PRINTLN to reduce the code size and make the source more readable
See: https://github.com/shirriff/Arduino-IRremote/issues/151

**Comment by z3t0** [comment]
@csBlueChip I am not sure if there is a lot of point in merging this, initially the approach I was planning on taking was to go from the Release version (there is only one) and build up from there in compliance to the commits on this branch. If you want you can go ahead and reset experimental to the release and then make a pull request from there. The only reason I say this is because we know that everything is functional in that.

Sorry for any hassles

**Comment by csBlueChip** [comment]
@z3t0 If I'm entirely honest, I'm afraid I don't really understand what you are suggesting :/ Perhaps it would be better if I retract this/these pull request(s) and let you progress as you intended.

@SecretFireSoftware The changes I have proposed so far are merely pulling the code in to a single coding style so I (& others) can quickly and easily see what is going on. Once I can fly up-and-down the source code at speed, I planned to implement a bunch of code optimisations (speed & memory improvements) and add more encoding standards (EG. My Denon amp) ...My ultimate personal goal is to build an "engineers" remote control unit (and, ?of course?, submit the whole project to the open source/hardware community)

**Comment by SecretFireSoftware** [comment]
My comment was specifically about the one-line-ifs. I was curious as to why you thought that was a good idea.

**Comment by csBlueChip** [comment]
@SecretFireSoftware : 1) Functions which exist entirely on one screen of code are *considerably* easier to comprehend/maintain/debug than functions which cover multiple screens; reducing 9 lines of code down to 3 aids this; 2) I notice that it had already been deemed an acceptable style as it is used in the RC6 code (although in fariness there are any number of obscure coding practices in this block of code); 3) taking this as a random example:
```
    if (MATCH_SPACE(results->rawbuf[offset],PANASONIC_ONE_SPACE)) {
      data = (data << 1) | 1;
    } else if (MATCH_SPACE(results->rawbuf[offset],PANASONIC_ZERO_SPACE)) {
        data <<= 1;
    } else {
        return ERR;
    }
```
I propose that it is considerably easier to see what is happening if the exact same code is formatted as:
```
    if      (MATCH_SPACE(results->rawbuf[offset], PANASONIC_ONE_SPACE ))  data   = (data << 1) | 1 ;
    else if (MATCH_SPACE(results->rawbuf[offset], PANASONIC_ZERO_SPACE))  data <<= 1 ;
    else                                                                  return ERR ;
```

**Comment by csBlueChip** [comment]
I am going to continue working with the Master branch as a) it supports more standards and b) I simply failed to understand the z3t0's suggestion ...I will leave the pull-request open in case someone cares to see my work ...if anyone would rather I close it, just say so and it will be done.

**Comment by z3t0** [comment]
@csBlueChip No offence was meant, I see what you mean. In that case I will rebase all my changes off of this pull request and will be submitting 2.0 in about a weeks time, when I should be free to work on this to my hearts content :smile: 

P.S: Please don't take anything I say personally

**Comment by csBlueChip** [comment]
@z3t0 No offence taken. This great work has saved me weeks of painful reverse engineering.

**Comment by csBlueChip** [comment]
@z3t0 Well, I have got the library to a place where I will now move forward and start to implement it in my project. I have left this pull request open, so please feel free to take anything you like and leave things you don't like, although it's now quite a significant overhaul of the code, so it's probably a bit of all-or-nothing now ..I have submitted potentially worrying things I have found along the way as "issues" on the "origin" - all-in-all the source base was pretty stable - nice work everyone :) ...If you have ANY questions for me, just "@" me and I'll get an email from github to let me know :)

**Comment by z3t0** [comment]
@csBlueChip Thanks for all your hard work! I will make sure to merge this as soon as I have some time (most likely next week)

**Comment by z3t0** [comment]
merged into experimental. Will release after testing

**Comment by z3t0** [comment]
Closing as it is already in experimental and close to release.

**Pull request closed without merging**
