### PR TITLE
Added possibility to exclude non-necessary libraries to reduce code size

### PR DESCRIPTION
**Pull request by sstefanov**

### CODE REVIEW

**Comment by z3t0** [comment]
Thanks! I'll test and report back results.

**Comment by z3t0** [comment]
@sstefanov Does this produce measurable changes? I am interested because I remember closing an issue for a board with very limited space, so this could open possibilities for further support.

**Comment by joshuajnoble** [comment]
I like this and unless @shirriff or @PaulStoffregen objects would like to merge it since there are so many different IR protocols and the code bloat to support all of them would make the library cumbersome to use with other libs on boards with limited space.

**Comment by sstefanov** [comment]
When only one receiving protocol is enabled hex code is around 4 k less
than case when all send and receiving functions are enabled.
На 14.03.2015 00:32 "Rafi Khan" <notifications@github.com> написа:

**Comment by z3t0** [comment]
@joshuajnoble Agreed. Should we merge this into the experimental branch then and add this feature to the new decoding that has already been added there?

**Comment by z3t0** [comment]
@sstefanov Thanks for the specific details and also the work, that sounds like a huge prospect for those boards with limited space.

**Comment by sstefanov** [comment]
I just made some tests and there are results (code is for remote controlled player). Size is for all code, not only for IR remote library:

All sending and receiving functions enabled:
Binary sketch size: 21314 bytes (of a 30720 byte maximum, 69.38 percent).

Only NEC receiving enbled:
Binary sketch size: 17918 bytes (of a 30720 byte maximum, 58.33 percent).

Only RC5 enabled:
Binary sketch size: 18926 bytes (of a 30720 byte maximum, 61.61 percent).

**Comment by z3t0** [comment]
Awesome improvements. This will be merged as soon as @joshuajnoble and myself decide on the best approach to model a stable development system. Checkout #107 to get in on the conversation.

**Comment by crash7** [comment]
Hi all,
Would be better to split the file in nec, rc5, sharp, etc. instead of using #ifdef everywhere? 
What do you think?

**Comment by z3t0** [comment]
@crash7 sure we could do that.

**Comment by joshuajnoble** [comment]
That makes more sense from a code perspective but it breaks the Arduino convention of having a single .h file to import the whole library, thus enabling the "Import Library" tool to just work.

Obligatory phone disclaimer

**Comment by crash7** [comment]
@joshuajnoble true, nevermind then.

**Comment by z3t0** [comment]
Oh sorry I misread, I thought you meant into separate PRs.

**Pull request merged**
