### PR TITLE
Allow timer selection via #define

### PR DESCRIPTION
**Pull request by tomdeboer**
This allows you to select which timer you want to use without touching IRremoteInt.h

You can `#define IR_USE_TIMER1` for example, to use Timer1 instead of the default (on Arduino) Timer2

### CODE REVIEW

**Comment by z3t0** [comment]
@tomdeboer has this been tested?

**Comment by tomdeboer** [comment]
No I'm afraid not.. It did work, but not in the Arduino IDE, only in Sublime or build file. Maybe you can give it another try.

**Comment by z3t0** [comment]
OK I'll see if I can get it working

**Comment by z3t0** [comment]
Does this work for all arduinos or only mega.  What would be a test sketch for an arduino uno?

If we get this working we may unlock support for alot more boards

**Comment by z3t0** [comment]
What errors did you get when using the Arduino IDE

**Comment by tomdeboer** [comment]
The problem with the Arduino IDE is that if you ```#define IR_USE_TIMER4``` in your .ino, the ```#if IR_USE_TIMER4``` would still evaluate false. I'm not sure, but I think the build file the IDE uses includes all the libraries includes all headers before the actual ```#include``` in your script. At that point your define isn't setup yet.

**Comment by z3t0** [comment]
hmm

**Comment by z3t0** [comment]
Just found this 
'''
The Arduino pre-processor doesn't understand #ifdef's or other pre-processor directives.  It links in libraries placed within "#if 0" and other false checks.  It also places the automatically generated function prototypes without regard for these directives, which often leads to various problems.  

This is tricky to fix and to test (there are lots of different cases).  For now, you may want to avoid the use of #ifdefs and #if 0 in your sketch or, at least, for commenting out unused libraries or at the beginning of your sketch (using them later in the code shouldn't affect the placement of the function prototypes).  
'''

**Comment by z3t0** [comment]
"The #ifdefs work fine in .cpp, .c, and .h files, since those aren't pre-processed (that includes files in libraries, like in the tutorial you reference).  They work in your sketch files (.ino files) too but can interact with the Arduino pre-processor in ways that lead to the errors people have seen.  " - [here](https://code.google.com/p/arduino/issues/detail?id=906)

**Comment by z3t0** [comment]
@tomdeboer How would we test this? To check if it actually works

**Comment by tomdeboer** [comment]
Maybe you can create a separate .h and .cpp file with a setup and loop? In which you define your timer and include the IRremote.h (in that order). Because as I read that post correctly, .cpp files aren't processed by Arduino's pre-processor.

**Comment by z3t0** [comment]
I'll see what I can do

**Comment by z3t0** [comment]
Is there any way to test if it is using the timer we specify?

**Comment by tomdeboer** [comment]
Maybe you can just use something like ```#warning "No time specified"``` if the #ifdef evaluates false.

**Comment by z3t0** [comment]
@tomdeboer Would it make more sense to just create a page on the wiki explaining how to do this manually from within the library? I think that would be the simplest approach, see https://github.com/khair-eddine/Arduino-IRremote/pull/1/files

**Comment by z3t0** [comment]
This is being closed as the approach does not work with the Arduino IDE.

**Pull request closed without merging**
