### PR TITLE
Added Aiwa protocol (remote control RC-T501).

### PR DESCRIPTION
**Pull request by crash7**
Added Aiwa protocol (remote control RC-T501) based on lirc file.
Updated IRrecvDump example, added SendDemo example (AiwaRCT501SendDemo).

### CODE REVIEW

**Comment by z3t0** [comment]
WIP

**Comment by crash7** [comment]
I should update this PR, is the project active again?

**Comment by z3t0** [comment]
The project is currently active and hopefully will be experience further development. Please update the PR so that we can think about merging it. Thanks for the contribution

**Comment by crash7** [comment]
@z3t0 thanks for your answer. I updated the PR, should i close this and submit this against the experimental branch?

**Comment by z3t0** [comment]
I would like to keep the experimental branch fairly stable so I have marked this as awaiting merge, I want to try and take things one step at at time with major PR's like this one. What do you think?

**Comment by z3t0** [comment]
Nevermind, I'll take another look make some changes and merge.

**Comment by crash7** [comment]
@z3t0 ok, let me know if you need help :) thanks for taking care of all the pending PRs!

**Comment by z3t0** [comment]
No problem! I'll add your name to the collaborators list on the README.md, if you don't mind?

**Comment by crash7** [comment]
@z3to sure! :)

**Comment by z3t0** [comment]
Done!

**Comment by z3t0** [comment]
Please check #107 I merged this into there manually.

**Comment by crash7** [comment]
@z3t0 i was about to create a new PR but this is still valid, please re-open and i will update after #110 is merged.

**Comment by z3t0** [comment]
@crash7 Sorry for the delay.

**Comment by z3t0** [comment]
@sstefanov Thanks for the contribution!

**Comment by z3t0** [comment]
Please check the beta build to see the drastic improvements in performance! I'll make it an official build once we have some results back. (Removing the other disastrous beta build :smile: )

**Comment by z3t0** [comment]
So sorry! I accidentally merged the wrong one...
Should I unmerge this then merge #113 ?

**Comment by crash7** [comment]
@z3t0 i can do a new patch after #113 is merged to add the missings #ifdef, don't worry.

**Comment by z3t0** [comment]
ok thanks!

**Pull request merged**
