### PR TITLE
Sharp decoding support

### PR DESCRIPTION
**Pull request by Informatic**
That one should be better...

### CODE REVIEW

**Comment by z3t0** [comment]
@Informatic Is this not already supported?

**Comment by Informatic** [comment]
Seems like it's not.

**Comment by z3t0** [comment]
I do not know for sure, but searching for "sharp" in the repository shows quite a lot of instances in the code being named so, suggesting that it is supported?

**Comment by Informatic** [comment]
Only Sharp transmission code (which i remember to have slighty rewritten in
#84) is present in master right now.

That PR implements Sharp decoding.

**Comment by z3t0** [comment]
OK my bad. I'll take a look and merge it.

**Comment by z3t0** [comment]
I am merging this into the experimental branch for now. I don't think any one will test it... so I'll leave it there for a day or two with an open pull request. Please re-test the pull request from the experimental branch and report your results there. Thanks for the contribution!

**Comment by z3t0** [comment]
@Informatic This has been reopened because there seems to be un-merged changes on your repository.

```
On branch Informatic-decodesharp
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

        modified:   IRremoteInt.h
        modified:   examples/IRrecvDump/IRrecvDump.ino

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   IRremote.cpp
        both modified:   IRremote.h
        both modified:   keywords.txt
```

Please fix above so that I can merge it into the branch

**Comment by z3t0** [comment]
Actually... Sorry I think that was my fault. Hmm

**Comment by z3t0** [comment]
Hi can you please help me. Running the commands below cause merge conflicts, but I just want to clone your branch into a new one. Obviously its not up to speed with master, so what do I do?
```
git checkout -b Informatic-decodesharp master
git pull https://github.com/Informatic/Arduino-IRremote.git decodesharp
```

**Comment by z3t0** [comment]
I figured out that I need to fix the merge conflicts.

Here's one I am not sure about.
```
<<<<<<< HEAD
#define WHYNTER 13
=======
#define SHARP 13
>>>>>>> 0b9d907da992bbb56493164e79d37006ec52e777
#define UNKNOWN -1
```
That is in IRremote.h

Do I just change SHARP to 14? Is there anywhere else it needs to be changed.

**Comment by z3t0** [comment]
Can you also please take a look here:

```
<<<<<<< HEAD
long IRrecv::decodeWhynter(decode_results *results) {
  long data = 0;
  
  if (irparams.rawlen < 2 * WHYNTER_BITS + 6) {
     return ERR;
  }
  
  int offset = 1; // skip initial space

  // sequence begins with a bit mark and a zero space
  if (!MATCH_MARK(results->rawbuf[offset], WHYNTER_BIT_MARK)) {
    return ERR;
  }
  offset++;
  if (!MATCH_SPACE(results->rawbuf[offset], WHYNTER_ZERO_SPACE)) {
    return ERR;
  }
  offset++;

  // header mark and space
  if (!MATCH_MARK(results->rawbuf[offset], WHYNTER_HDR_MARK)) {
    return ERR;
  }
  offset++;
  if (!MATCH_SPACE(results->rawbuf[offset], WHYNTER_HDR_SPACE)) {
    return ERR;
  }
  offset++;

  // data bits
  for (int i = 0; i < WHYNTER_BITS; i++) {
    if (!MATCH_MARK(results->rawbuf[offset], WHYNTER_BIT_MARK)) {
      return ERR;
    }
    offset++;
    if (MATCH_SPACE(results->rawbuf[offset], WHYNTER_ONE_SPACE)) {
      data = (data << 1) | 1;
    } 
    else if (MATCH_SPACE(results->rawbuf[offset],WHYNTER_ZERO_SPACE)) {
=======
long IRrecv::decodeSharp(decode_results *results) {
  long data = 0;
  if (irparams.rawlen < 32) {
    return ERR;
  }

  int offset = 0; // Dont skip first space, check its size
  
  if (results->rawbuf[offset] < SHARP_RPT_SPACE) {
    // Serial.print("IR Gap found: ");
    results->bits = 0;
    results->value = REPEAT;
    results->decode_type = SHARP;
    return DECODED;
  }
  
  offset++;
  
  while (offset + 1 < irparams.rawlen) {
    if (!MATCH_MARK(results->rawbuf[offset], SHARP_BIT_MARK)) {
      break;
    }
    offset++;
    if (MATCH_SPACE(results->rawbuf[offset], SHARP_ONE_SPACE)) {
      data = (data << 1) | 1;
    } 
    else if (MATCH_SPACE(results->rawbuf[offset], SHARP_ZERO_SPACE)) {
>>>>>>> 0b9d907da992bbb56493164e79d37006ec52e777
      data <<= 1;
    } 
    else {
      return ERR;
    }
    offset++;
  }
<<<<<<< HEAD
  
  // trailing mark
  if (!MATCH_MARK(results->rawbuf[offset], WHYNTER_BIT_MARK)) {
    return ERR;
  }
  // Success
  results->bits = WHYNTER_BITS;
  results->value = data;
  results->decode_type = WHYNTER;
  return DECODED;
}


=======

  if (data & 1 || !(data & 2)) {
    return ERR;
  }

  // Success
  results->bits = (offset - 1) / 2;
  if (results->bits < 15) {
    results->bits = 0;
    return ERR;
  }
  
  results->sharpAddress = (data >> 10) & 0b11111;
  results->value = (data >> 2) & 0xff;
  results->decode_type = SHARP;
  return DECODED;
}

>>>>>>> 0b9d907da992bbb56493164e79d37006ec52e777
```

Sorry I am not too much help, I don't know a lot about the code of this library yet.

**Comment by z3t0** [comment]
3722d6a0cbcbedbc13cb2d1c66f771f06cb97c37
Please report any errors after testing from the experimental branch

**Comment by z3t0** [comment]
@Informatic Please check #107

**Pull request closed without merging**
