### PR TITLE
Continuous Integration with @travis-ci + @PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**
More details http://docs.platformio.org/en/latest/ci/travis.html

@shirriff Please enable https://travis-ci.org for this project. See step 1, 2, and step 4 here: http://docs.travis-ci.com/user/getting-started/

It should look like https://travis-ci.org/ivankravets/Arduino-IRremote

Comments are welcome!

### CODE REVIEW

**Comment by z3t0** [comment]
Thanks for the PR. This looks like a great idea, I will look a bit further into travis and then merge the PR.

**Comment by z3t0** [comment]
Hmm. I am trying to figure out how this works and am a little confused as to why the language is set to python and not c?

**Comment by z3t0** [comment]
@ivankravets I just tried to manually merge this... didnt work...
https://github.com/shirriff/Arduino-IRremote/commit/b79c04f11c675a58829e2f2e8cd1a71bdd816e06

@shirriff Could you enable Travis CI on this? I think the owner of the repository has to enable something for it to work? (not sure)

**Comment by z3t0** [comment]
Update: Only those with admin access can enable Travis CI.

@ivankravets @shirriff

**Comment by ivankravets** [comment]
Dear @z3t0,

> Hmm. I am trying to figure out how this works and am a little confused as to why the language is set to python and not c?

PlatformIO is written in Python. This is a quick way to setup Python environment on Travis worker. You don't need to bother with this type of project, because PlatformIO uses own source code builder and toolchains.

**Comment by z3t0** [comment]
@ivankravets Thanks for the contribution!!! Travis CI is now working... will get to work the build failing errors ASAP.

Your contribution is GREATLY appreciated

@shirriff Thanks for going through the setup of Travis

**Comment by ivankravets** [comment]
Please merge my pull-request with updated badge https://github.com/z3t0/Arduino-IRremote/pull/182

Thanks in advance!

**Pull request merged**
